### ISSUE TITLE
Badly written code

### ISSUE THREAD

**Issue by JuqnDev** [MarlonDevPMMP/XBooster#3]
I have seen your code and I think you have errors. In the commands when you use foreach, what are they for?
You are simply misusing it and repeatedly telling the player executing the command to do actions.

**Comment by MarlonDevPMMP** [comment]
I'm a noob and used what i got when someone helped me. The most is my one but some things are from other Discords that helped me. But there are 100% no errors. Ist tested the completely Plugin for like an our and there are no error or bugs.

**Comment by MarlonDevPMMP** [comment]
I would like that you delete your fork please. I only don't know how to deactivate forks. Thank you for your feedback!

**Comment by JuqnDev** [comment]
I know that you are just starting in this world and that is why I want to help you. If you see, foreach are creating TASK constants so it can cause server lag. What do you really want to do?

**Comment by MarlonDevPMMP** [comment]
I used foreach to get every player on the server

**Comment by MarlonDevPMMP** [comment]
I mean it's ok that you forked it, but.. Please edit the readme.md that i made this plugin and you fixxed some things.

**Comment by JuqnDev** [comment]
I know but when you use a foreach all the actions that are inside it, it does. You are making it generate a task but the task uses another foreach

**Comment by MarlonDevPMMP** [comment]
Ok lol. For me everything worked on the test server, so.. But thank you for helping me! I world be happy if you join my community server. Link is in the README.md of XBooster
